enable: true
type: "message"
#message - сообщение в чате title - вывод в тайтл
time: 4
# сколько по времени игрок видит тайтл
message:
  - "&bвас пингует игрок %player%"
  - "&lпожалуйста ответьте ему)))"
#после сообщения идет имя игрока который вас пинганул
title: "&bвас пингует игрок %player%"
TagDisabled: "&bвы отключили тег себя!"
TagEnabled: "&bвы включили возможность тегать вас!"
Sound: "BLOCK_NOTE_BLOCK_BELL"